config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :guards
  resources :appointments
  resources :workers
  resources :worker_types
  resources :medical_centers
  resources :medical_center_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "medical_centers#index"
end

app/controllers/medical_center_types_controller.rb
class MedicalCenterTypesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_medical_center_type, only: %i[ show edit update destroy ]

  # GET /medical_center_types or /medical_center_types.json
  def index
    @medical_center_types = MedicalCenterType.all
  end

  # GET /medical_center_types/1 or /medical_center_types/1.json
  def show
  end

  # GET /medical_center_types/new
  def new
    @medical_center_type = MedicalCenterType.new
  end

  # GET /medical_center_types/1/edit
  def edit
  end

  # POST /medical_center_types or /medical_center_types.json
  def create
    @medical_center_type = MedicalCenterType.new(medical_center_type_params)

    respond_to do |format|
      if @medical_center_type.save
        format.html { redirect_to @medical_center_type, notice: "Medical center type was successfully created." }
        format.json { render :show, status: :created, location: @medical_center_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medical_center_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_center_types/1 or /medical_center_types/1.json
  def update
    respond_to do |format|
      if @medical_center_type.update(medical_center_type_params)
        format.html { redirect_to @medical_center_type, notice: "Medical center type was successfully updated." }
        format.json { render :show, status: :ok, location: @medical_center_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medical_center_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_center_types/1 or /medical_center_types/1.json
  def destroy
    @medical_center_type.destroy
    respond_to do |format|
      format.html { redirect_to medical_center_types_url, notice: "Medical center type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_center_type
      @medical_center_type = MedicalCenterType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medical_center_type_params
      params.require(:medical_center_type).permit(:name, :description)
    end
end

app/helpers/medical_center_types_helper.rb
module MedicalCenterTypesHelper
end

app/views/medical_center_types/_form.html.erb
<%= form_with(model: medical_center_type) do |form| %>
  <% if medical_center_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medical_center_type.errors.count, "error") %> prohibited this medical_center_type from being saved:</h2>

      <ul>
        <% medical_center_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medical_center_types/edit.html.erb
<h1>Editing Medical Center Type</h1>

<%= render 'form', medical_center_type: @medical_center_type %>

<%= link_to 'Show', @medical_center_type %> |
<%= link_to 'Back', medical_center_types_path %>

app/views/medical_center_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medical Center Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_center_types.each do |medical_center_type| %>
      <tr>
        <td><%= medical_center_type.name %></td>
        <td><%= medical_center_type.description %></td>
        <td><%= link_to 'Show', medical_center_type %></td>
        <td><%= link_to 'Edit', edit_medical_center_type_path(medical_center_type) %></td>
        <td><%= link_to 'Destroy', medical_center_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medical Center Type', new_medical_center_type_path %>

app/views/medical_center_types/new.html.erb
<h1>New Medical Center Type</h1>

<%= render 'form', medical_center_type: @medical_center_type %>

<%= link_to 'Back', medical_center_types_path %>

app/views/medical_center_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @medical_center_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @medical_center_type.description %>
</p>

<%= link_to 'Edit', edit_medical_center_type_path(@medical_center_type) %> |
<%= link_to 'Back', medical_center_types_path %>