config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :guards
  resources :appointments
  resources :workers
  resources :worker_types
  resources :medical_centers
  resources :medical_center_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "medical_centers#index"
end

app/models/guard.rb
class Guard < ApplicationRecord
  belongs_to :medical_center
  belongs_to :worker
  
  validates :guard_date, :uniqueness => true, :presence => true
end

app/controllers/guards_controller.rb
class GuardsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_guard, only: %i[ show edit update destroy ]

  # GET /guards or /guards.json
  def index
    @guards = Guard.all
  end

  # GET /guards/1 or /guards/1.json
  def show
  end

  # GET /guards/new
  def new
    @guard = Guard.new
  end

  # GET /guards/1/edit
  def edit
  end

  # POST /guards or /guards.json
  def create
    @guard = Guard.new(guard_params)

    respond_to do |format|
      if @guard.save
        format.html { redirect_to @guard, notice: "Guard was successfully created." }
        format.json { render :show, status: :created, location: @guard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guards/1 or /guards/1.json
  def update
    respond_to do |format|
      if @guard.update(guard_params)
        format.html { redirect_to @guard, notice: "Guard was successfully updated." }
        format.json { render :show, status: :ok, location: @guard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guards/1 or /guards/1.json
  def destroy
    @guard.destroy
    respond_to do |format|
      format.html { redirect_to guards_url, notice: "Guard was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guard
      @guard = Guard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guard_params
      params.require(:guard).permit(:guard_date, :medical_center_id, :worker_id)
    end
end

app/helpers/guards_helper.rb
module GuardsHelper
end

app/views/guards/_form.html.erb
<%= form_with(model: guard) do |form| %>
  <% if guard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guard.errors.count, "error") %> prohibited this guard from being saved:</h2>

      <ul>
        <% guard.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :guard_date %>
    <%= form.datetime_select :guard_date %>
  </div>

  <div class="field">
    <%= form.label :medical_center_id %>
    <%= form.collection_select(:medical_center_id, MedicalCenter.all, :id, :name)  %>
  </div>

  <div class="field">
    <%= form.label :worker_id %>
    <%= form.collection_select(:worker_id, Worker.all, :id, :first_name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guards/edit.html.erb
<h1>Editing Guard</h1>

<%= render 'form', guard: @guard %>

<%= link_to 'Show', @guard %> |
<%= link_to 'Back', guards_path %>

app/views/guards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guards</h1>

<table>
  <thead>
    <tr>
      <th>Guard date</th>
      <th>Medical center</th>
      <th>Worker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guards.each do |guard| %>
      <tr>
        <td><%= guard.guard_date %></td>
        <td><%= guard.medical_center_id %></td>
        <td><%= guard.worker_id %></td>
        <td><%= link_to 'Show', guard %></td>
        <td><%= link_to 'Edit', edit_guard_path(guard) %></td>
        <td><%= link_to 'Destroy', guard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guard', new_guard_path %>

app/views/guards/new.html.erb
<h1>New Guard</h1>

<%= render 'form', guard: @guard %>

<%= link_to 'Back', guards_path %>

app/views/guards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guard date:</strong>
  <%= @guard.guard_date %>
</p>

<p>
  <strong>Medical center:</strong>
  <%= @guard.medical_center_id %>
</p>

<p>
  <strong>Worker:</strong>
  <%= @guard.worker_id %>
</p>

<%= link_to 'Edit', edit_guard_path(@guard) %> |
<%= link_to 'Back', guards_path %>