config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :guards
  resources :appointments
  resources :workers
  resources :worker_types
  resources :medical_centers
  resources :medical_center_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "medical_centers#index"
end

app/controllers/worker_types_controller.rb
class WorkerTypesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_worker_type, only: %i[ show edit update destroy ]

  # GET /worker_types or /worker_types.json
  def index
    @worker_types = WorkerType.all
  end

  # GET /worker_types/1 or /worker_types/1.json
  def show
  end

  # GET /worker_types/new
  def new
    @worker_type = WorkerType.new
  end

  # GET /worker_types/1/edit
  def edit
  end

  # POST /worker_types or /worker_types.json
  def create
    @worker_type = WorkerType.new(worker_type_params)

    respond_to do |format|
      if @worker_type.save
        format.html { redirect_to @worker_type, notice: "Worker type was successfully created." }
        format.json { render :show, status: :created, location: @worker_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worker_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worker_types/1 or /worker_types/1.json
  def update
    respond_to do |format|
      if @worker_type.update(worker_type_params)
        format.html { redirect_to @worker_type, notice: "Worker type was successfully updated." }
        format.json { render :show, status: :ok, location: @worker_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worker_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worker_types/1 or /worker_types/1.json
  def destroy
    @worker_type.destroy
    respond_to do |format|
      format.html { redirect_to worker_types_url, notice: "Worker type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker_type
      @worker_type = WorkerType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worker_type_params
      params.require(:worker_type).permit(:name, :description)
    end
end

app/helpers/worker_types_helper.rb
module WorkerTypesHelper
end

app/views/worker_types/_form.html.erb
<%= form_with(model: worker_type) do |form| %>
  <% if worker_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker_type.errors.count, "error") %> prohibited this worker_type from being saved:</h2>

      <ul>
        <% worker_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/worker_types/edit.html.erb
<h1>Editing Worker Type</h1>

<%= render 'form', worker_type: @worker_type %>

<%= link_to 'Show', @worker_type %> |
<%= link_to 'Back', worker_types_path %>

app/views/worker_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Worker Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worker_types.each do |worker_type| %>
      <tr>
        <td><%= worker_type.name %></td>
        <td><%= worker_type.description %></td>
        <td><%= link_to 'Show', worker_type %></td>
        <td><%= link_to 'Edit', edit_worker_type_path(worker_type) %></td>
        <td><%= link_to 'Destroy', worker_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker Type', new_worker_type_path %>

app/views/worker_types/new.html.erb
<h1>New Worker Type</h1>

<%= render 'form', worker_type: @worker_type %>

<%= link_to 'Back', worker_types_path %>

app/views/worker_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @worker_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @worker_type.description %>
</p>

<%= link_to 'Edit', edit_worker_type_path(@worker_type) %> |
<%= link_to 'Back', worker_types_path %>